// ***********************************************************************
// Assembly         : 
// Author           : Tim
// Created          : 07-10-2017
//
// Last Modified By : Tim
// Last Modified On : 08-01-2017
// ***********************************************************************
// <copyright file="createnewprofile.h" company="">
//     Copyright (c) 2017,  eNVy Systems, Inc. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
#ifndef CREATENEWPROFILE_H
#define CREATENEWPROFILE_H

#include <QDialog>
#include <QDateTime>
#include "nvProfilesClass.h"

/// <summary>
/// The Ui namespace.
/// </summary>
namespace Ui {
class CreateNewProfile;
}

/// <summary>
/// Class CreateNewProfile.
/// </summary>
/// <seealso cref="QDialog" />
class CreateNewProfile : public QDialog
{
	Q_OBJECT

public:
	void initialize(nvProfilesClass * profClass) const;

	/// <summary>
	/// Initializes a new instance of the <see cref="CreateNewProfile" /> class.
	/// </summary>
	/// <param name="parent">The parent.</param>
	explicit CreateNewProfile(QWidget *parent = nullptr);
	/// <summary>
	/// Destructor for an instance of the <see cref="CreateNewProfile"/> class.
	/// </summary>
	virtual ~CreateNewProfile() override;
	/// <summary>
	/// Sets the edit enabled.
	/// </summary>
	/// <autogeneratedoc />
	/// TODO Edit XML Comment Template for setEditEnabled
	void	setEditEnabled();

public slots:

private slots:
    void on_pushButton_profileCheck_clicked();

/// <summary>
/// Ons the push button edit profile clicked.
/// </summary>
	void on_pushButton_editProfile_clicked();


	/// <summary>
	/// Ons the list widget double clicked.
	/// </summary>
	/// <param name="index">The index.</param>
	void on_listWidget_doubleClicked(const QModelIndex &index);


	/// <summary>
	/// Ons the push button commit clicked.
	/// </summary>
	void on_pushButton_Commit_clicked();


	/// <summary>
	/// Ons the button box accepted.
	/// </summary>
	void on_buttonBox_accepted();


	/// <summary>
	/// Ons the button box rejected.
	/// </summary>
	void on_buttonBox_rejected();


	/// <summary>
	/// Ons the push button generate clicked.
	/// </summary>
	void on_pushButton_Generate_clicked();


	/// <summary>
	/// Ons the line edit text edited.
	/// </summary>
	/// <param name="arg1">The arg1.</param>
	void on_lineEdit_textEdited(const QString &arg1);


	/// <summary>
	/// Ons the check box profile enabled state changed.
	/// </summary>
	/// <param name="arg1">The arg1.</param>
	void on_checkBox_ProfileEnabled_stateChanged(int arg1);



	/// <summary>
	/// Ons the check box automatic commit enabled state changed.
	/// </summary>
	/// <param name="arg1">The arg1.</param>
	void on_checkBox_AutoCommitEnabled_stateChanged(int arg1);


	/// <summary>
	/// Ons the check box profile trace enabled state changed.
	/// </summary>
	/// <param name="arg1">The arg1.</param>
	void on_checkBox_ProfileTraceEnabled_stateChanged(int arg1);


	/// <summary>
	/// Ons the check box profile transaction logging state changed.
	/// </summary>
	/// <param name="arg1">The arg1.</param>
	void on_checkBox_ProfileTransactionLogging_stateChanged(int arg1);


	/// <summary>
	/// Ons the spin box commit throttle value changed.
	/// </summary>
	/// <param name="arg1">The arg1.</param>
	void on_spinBox_CommitThrottle_valueChanged(int arg1);


	/// <summary>
	/// Ons the spin box execution threads value changed.
	/// </summary>
	/// <param name="arg1">The arg1.</param>
	void on_spinBox_ExecutionThreads_valueChanged(int arg1);


	/// <summary>
	/// Ons the text edit text changed.
	/// </summary>
	void on_textEdit_textChanged();


	/// <summary>
	/// Ons the combo box logging level current index changed.
	/// </summary>
	/// <param name="index">The index.</param>
	void on_comboBox_loggingLevel_currentIndexChanged(int index);


	/// <summary>
	/// Ons the combo box drop target current index changed.
	/// </summary>
	/// <param name="index">The index.</param>
	void on_comboBox_dropTarget_currentIndexChanged(int index);


	/// <summary>
	/// Ons the push button log filebrowse clicked.
	/// </summary>
	void on_pushButton_LogFileBrowse_clicked();


	/// <summary>
	/// Ons the line edit log file name text changed.
	/// </summary>
	/// <param name="arg1">The arg1.</param>
	void on_lineEdit_LogFileName_textChanged(const QString &arg1);


	/// <summary>
	/// Ons the line edit text changed.
	/// </summary>
	/// <param name="arg1">The arg1.</param>
	void on_lineEdit_textChanged(const QString &arg1);


	/// <summary>
	/// Ons the push button delete profile clicked.
	/// </summary>
	void on_pushButton_deleteProfile_clicked();


	/// <summary>
	/// Ons the push button copy profile clicked.
	/// </summary>
	void on_pushButton_copyProfile_clicked();


	/// <summary>
	/// Ons the line edit copy profile name text changed.
	/// </summary>
	/// <param name="arg1">The arg1.</param>
	void on_lineEdit_copyProfileName_textChanged(const QString &arg1);

private:
	/// <summary>
	/// The UI
	/// </summary>
	Ui::CreateNewProfile *ui;
	/// <summary>
	/// The profile name
	/// </summary>
	QString profileName;
	/// <summary>
	/// The profile description
	/// </summary>
	QString profileDescription;
	/// <summary>
	/// The profile commit throttle
	/// </summary>
	int profileCommitThrottle;
	/// <summary>
	/// The profile execution threads
	/// </summary>
	int profileExecutionThreads;
	/// <summary>
	/// The profile enabled
	/// </summary>
	bool profileEnabled;
	/// <summary>
	/// The profile trace
	/// </summary>
	bool profileTrace;
	/// <summary>
	/// The profile autocommit
	/// </summary>
	bool profileAutocommit;
	/// <summary>
	/// The profile logging enabled
	/// </summary>
	bool profileLoggingEnabled;

	/// <summary>
	/// Updates the GUI.
	/// </summary>
	/// <param name="strMessage">The string message.</param>
	void  updateGui(QString strMessage);
	/// <summary>
	/// The profile TRG drop target
	/// </summary>
	int profileTrgDropTarget;
	/// <summary>
	/// The profile logging level
	/// </summary>
	int profileLoggingLevel;
	/// <summary>
	/// The string log file name
	/// </summary>
	QString strLogFileName;
	/// <summary>
	/// The b is profile copy
	/// </summary>
	bool  bIsProfileCopy;
	/// <summary>
	/// The b is profile edit
	/// </summary>
	bool  bIsProfileEdit;
};

#endif // CREATENEWPROFILE_H
