#include "qloggerwriter.h"

#include <QDir>
#include <QDateTime>
#include <QTextStream>
#include <QDebug>


/****************************************************************************************
 ** QLogger is a library to register and print logs into a file.
 ** Copyright (C) 2013  Francesc Martinez <es.linkedin.com/in/cescmm/en>
 **
 ** This library is free software; you can redistribute it and/or
 ** modify it under the terms of the GNU Lesser General Public
 ** License as published by the Free Software Foundation; either
 ** version 2.1 of the License, or (at your option) any later version.
 **
 ** This library is distributed in the hope that it will be useful,
 ** but WITHOUT ANY WARRANTY; without even the implied warranty of
 ** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 ** Lesser General Public License for more details.
 **
 ** You should have received a copy of the GNU Lesser General Public
 ** License along with this library; if not, write to the Free Software
 ** Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 ***************************************************************************************/

namespace QLogger
{
	/// <summary>
	/// qs the log trace.
	/// </summary>
	/// <param name="module">The module.</param>
	/// <param name="message">The message.</param>
	/// <autogeneratedoc />
	/// TODO Edit XML Comment Template for QLog_Trace
	void QLog_Trace(const QString &module, const QString &message)
    {
        QLog_(module, TraceLevel, message);
    }

	/// <summary>
	/// qs the log debug.
	/// </summary>
	/// <param name="module">The module.</param>
	/// <param name="message">The message.</param>
	/// <autogeneratedoc />
	/// TODO Edit XML Comment Template for QLog_Debug
	void QLog_Debug(const QString &module, const QString &message)
    {
        QLog_(module, DebugLevel, message);
    }

	/// <summary>
	/// qs the log information.
	/// </summary>
	/// <param name="module">The module.</param>
	/// <param name="message">The message.</param>
	/// <autogeneratedoc />
	/// TODO Edit XML Comment Template for QLog_Info
	void QLog_Info(const QString &module, const QString &message)
    {
        QLog_(module, InfoLevel, message);
    }

	/// <summary>
	/// qs the log warning.
	/// </summary>
	/// <param name="module">The module.</param>
	/// <param name="message">The message.</param>
	/// <autogeneratedoc />
	/// TODO Edit XML Comment Template for QLog_Warning
	void QLog_Warning(const QString &module, const QString &message)
    {
        QLog_(module, WarnLevel, message);
    }

	/// <summary>
	/// qs the log error.
	/// </summary>
	/// <param name="module">The module.</param>
	/// <param name="message">The message.</param>
	/// <autogeneratedoc />
	/// TODO Edit XML Comment Template for QLog_Error
	void QLog_Error(const QString &module, const QString &message)
    {
        QLog_(module, ErrorLevel, message);
    }

	/// <summary>
	/// qs the log fatal.
	/// </summary>
	/// <param name="module">The module.</param>
	/// <param name="message">The message.</param>
	/// <autogeneratedoc />
	/// TODO Edit XML Comment Template for QLog_Fatal
	void QLog_Fatal(const QString &module, const QString &message)
    {
        QLog_(module, FatalLevel, message);
    }

	/// <summary>
	/// qs the log.
	/// </summary>
	/// <param name="module">The module.</param>
	/// <param name="level">The level.</param>
	/// <param name="message">The message.</param>
	/// <autogeneratedoc />
	/// TODO Edit XML Comment Template for QLog_
	void QLog_(const QString &module, LogLevel level, const QString &message)
    {
        QLoggerManager *manager = QLoggerManager::getInstance();

        QMutexLocker(&manager->mutex);

        QLoggerWriter *logWriter = manager->getLogWriter(module);

        if (logWriter && logWriter->getLevel() <= level)
                logWriter->write(module,message);
    }

	/// <summary>
	/// Adds the destination.
	/// </summary>
	/// <param name="fileDest">The file dest.</param>
	/// <param name="modules">The modules.</param>
	/// <param name="level">The level.</param>
	/// <returns>bool.</returns>
	QLoggerManager * QLoggerManager::INSTANCE = NULL;

    QLoggerManager::QLoggerManager() : QThread(), mutex(QMutex::Recursive)
    {
        start();
    }

    QLoggerManager * QLoggerManager::getInstance()
    {
        if (!INSTANCE)
            INSTANCE = new QLoggerManager();

        return INSTANCE;
    }

    QString QLoggerManager::levelToText(const LogLevel &level)
    {
        switch (level)
        {
	
            case TraceLevel: return "Trace";
            case DebugLevel: return "Debug";
            case InfoLevel: return "Info";
            case WarnLevel: return "Warning";
            case ErrorLevel: return "Error";
            case FatalLevel: return "Fatal";
			case None: return "None";
            default: return QString();
        }
    }

    bool QLoggerManager::addDestination(const QString &fileDest, const QString &module, LogLevel level)
    {
        QLoggerWriter *log;

        if (!moduleDest.contains(module))
        {
            log = new QLoggerWriter(fileDest,level);
            moduleDest.insert(module, log);
            return true;
        }

        return false;
    }

    bool QLoggerManager::addDestination(const QString &fileDest, const QStringList &modules, LogLevel level)
    {
        QLoggerWriter *log;
		/// <summary>
		/// Foreaches the specified module.
		/// </summary>
		/// <param name="module">The module.</param>
		/// <param name="">The .</param>
		/// <returns>int.</returns>
		/// <autogeneratedoc />
		/// TODO Edit XML Comment Template for foreach
		foreach(QString module, modules)
        {
            if (!moduleDest.contains(module))
            {
                log = new QLoggerWriter(fileDest,level);
                moduleDest.insert(module, log);
                return true;
            }
        }
        return false;
    }

	/// <summary>
	/// Closes the logger.
	/// </summary>
	/// <autogeneratedoc />
	/// TODO Edit XML Comment Template for closeLogger
	void QLoggerManager::closeLogger()
    {
        //foreach (  QLoggerWriter *log,moduleDest)
        //{
        //	delete log;
        //}
        //moduleDest.clear();
        thread()->quit();
        exit(0);
        //deleteLater();

    }

    void QLoggerManager::removeAllDestination()
    {
        QList<QLoggerWriter*> myLogDest = moduleDest.values();
		/// <summary>
		/// Foreaches the specified wri.
		/// </summary>
		/// <param name="wri">The wri.</param>
		/// <param name="">The .</param>
		/// <returns>int.</returns>
		/// <autogeneratedoc />
		/// TODO Edit XML Comment Template for foreach
		foreach(QLoggerWriter *wri, myLogDest)
        {
            delete wri;
        }
        myLogDest.clear();
        moduleDest.clear();

    }

    QLoggerWriter::QLoggerWriter(const QString &fileDestination, LogLevel level)
    {
        m_fileDestination = fileDestination;
        m_level = level;
    }

	/// <summary>
	/// Writes the specified module.
	/// </summary>
	/// <param name="module">The module.</param>
	/// <param name="message">The message.</param>
	/// <autogeneratedoc />
	/// TODO Edit XML Comment Template for write
	void QLoggerWriter::write(const QString &module, const QString &message)
    {
        QString _fileName = m_fileDestination;

        int MAX_SIZE = 1024 * 1024;

        QDir dir(QDir::currentPath());
        if (!dir.exists("logs"))
            dir.mkdir("logs");

        QFile file(_fileName);
        QString toRemove = _fileName.section('.',-1);
        QString fileNameAux = _fileName.left(_fileName.size() - toRemove.size()-1);
        bool renamed = false;
        QString newName = fileNameAux + "_%1__%2.log";

        //Renomenem l'arxiu si està ple
        if (file.size() >= MAX_SIZE)
        {
            //Creem un fixer nou
            QDateTime currentTime = QDateTime::currentDateTime();
            newName = newName.arg(currentTime.date().toString("dd_MM_yy")).arg(currentTime.time().toString("hh_mm_ss"));
            renamed = file.rename(_fileName, newName);

        }

        file.setFileName(_fileName);
        if (file.open(QIODevice::ReadWrite | QIODevice::Text | QIODevice::Append))
        {
            QTextStream out(&file);
            QString dtFormat = QDateTime::currentDateTime().toString("dd-MM-yyyy hh:mm:ss.zzz");

            if (renamed)
                out << QString("%1 - Previous log %2\n").arg(dtFormat).arg(newName);

            QString logLevel = QLoggerManager::levelToText(m_level);
            QString text = QString("[%1] [%2] {%3} %4\n").arg(dtFormat).arg(logLevel).arg(module).arg(message);
            out << text;
            file.close();
        }
    }
}

